name: Terraform Destroy

on:
  workflow_dispatch:  # Manually triggered workflow

env:            
  AWS_REGION: ap-southeast-1  
  S3_BUCKET: sctp-ce8-tfstate
  TF_STATE_KEY: cornelia-activity.tfstate

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: destroy  # Requires manual approval in GitHub Environments

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform with S3 Backend
      run: terraform init -reconfigure

    - name: Destroy Infrastructure (Manual Confirmation)
      run: terraform destroy

    - name: Delete Terraform State File from S3
      run: aws s3 rm s3://$S3_BUCKET/$TF_STATE_KEY --region $AWS_REGION
