name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1  
  S3_BUCKET: cornelia-s3-bucket  

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: destroy

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init -reconfigure

    - name: Empty S3 Bucket Before Destroying
      run: aws s3 rm s3://$S3_BUCKET --recursive --region $AWS_REGION || true

    - name: Destroy Only S3 Bucket Resource
      run: terraform destroy -target=aws_s3_bucket.my_bucket -auto-approve
