name: Terraform Destroy S3 Bucket

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1  
  S3_BUCKET: cornelia-s3-bucket  

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: destroy

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: terraform init -reconfigure

    - name: Import S3 Bucket to Terraform (If Not Tracked)
      run: terraform import aws_s3_bucket.my_bucket $S3_BUCKET || true

    - name: Empty S3 Bucket (Including Versioned Objects)
      run: |
        aws s3 rm s3://$S3_BUCKET --recursive --region $AWS_REGION || true
        versions=$(aws s3api list-object-versions --bucket $S3_BUCKET --query 'Versions[].{Key:Key,VersionId:VersionId}' --output json --region $AWS_REGION)
        markers=$(aws s3api list-object-versions --bucket $S3_BUCKET --query 'DeleteMarkers[].{Key:Key,VersionId:VersionId}' --output json --region $AWS_REGION)

        echo $versions | jq -c '.[]' | while read i; do
          key=$(echo $i | jq -r '.Key')
          version_id=$(echo $i | jq -r '.VersionId')
          aws s3api delete-object --bucket $S3_BUCKET --key "$key" --version-id "$version_id" --region $AWS_REGION
        done

        echo $markers | jq -c '.[]' | while read i; do
          key=$(echo $i | jq -r '.Key')
          version_id=$(echo $i | jq -r '.VersionId')
          aws s3api delete-object --bucket $S3_BUCKET --key "$key" --version-id "$version_id" --region $AWS_REGION
        done

    - name: Destroy Only S3 Bucket Resource
      run: terraform destroy -target=aws_s3_bucket.my_bucket -auto-approve || true

    - name: Delete S3 Bucket (If Terraform Fails)
      run: aws s3api delete-bucket --bucket $S3_BUCKET --region $AWS_REGION || true
